// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmtlnitrlchcuibbljug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtdGxuaXRybGNoY3VpYmJsanVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NjYwMjQsImV4cCI6MjA2OTU0MjAyNH0.fgh8ikPxUpaSe2WHe3kDpGPBMPy9jMOB_CzZ1FAAH0Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});